[features]
seeds = false
skip-lint = false

[programs.devnet]
multisig_lite = "Ecycmji8eeggXrA3rD2cdEHpHDnP4btvVfcyTBS9cG9t"

[programs.localnet]
multisig_lite = "Ecycmji8eeggXrA3rD2cdEHpHDnP4btvVfcyTBS9cG9t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
fmt = "cargo fmt && yarn lint:fix"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
