name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  SOLANA_VERSION: v1.15.0
  PROGRAM_ID: Ecycmji8eeggXrA3rD2cdEHpHDnP4btvVfcyTBS9cG9t

defaults:
  run:
    shell: bash

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Run cargo fmt
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - run: cargo clippy --all-features --all-targets

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Run cargo check
        run: |
          cargo check --all-features --all-targets --bins --examples

  build-sbf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install Solana and SBF toolchain
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/$SOLANA_VERSION/install)"
      - name: Add solana command to the PATH environment
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - name: Run cargo build-sbf
        run: cargo build-sbf --workspace

  test-sbf:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install Solana and SBF toolchain
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/$SOLANA_VERSION/install)"
      - name: Add solana command to the PATH environment
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - name: Run cargo test-sbf
        run: cargo test-sbf --workspace

  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install Solana and SBF toolchain
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/$SOLANA_VERSION/install)"
      - name: Add solana command to the PATH environment
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - name: Run cargo build-sbf
        run: cargo build-sbf --workspace
      - name: Create a default signer
        run: solana-keygen new --no-bip39-passphrase
      - name: Set the local cluster
        run: solana config set -u localhost
      - name: Run local validator with the program
        run: |
          solana-test-validator -r -q --bpf-program $PROGRAM_ID ./target/deploy/multisig_lite.so
      - name: Run create multisig example
        run: cargo run --example create
      - name: Run close multisig example
        run: cargo run --example close

  anchor-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install Solana and BPF toolchain
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/$SOLANA_VERSION/install)"
      - name: Add solana command to the PATH environment
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install Anchor-cli
        run: cargo install anchor-cli
      - name: Run anchor build
        run: anchor build
